### ISSUE TITLE
Implement Dispatched/Undispatched commits concept

### ISSUE THREAD

**Issue by joaodiasneves** [GuzzoLM/EventLite#18]
conceito de undispatched/dispatched commits (isto é importante para o proprio conceito de event sourcing. Se tá commited, temos de garantir que foi dispatched).

**Comment by GuzzoLM** [comment]
A idéia dessa biblioteca é apenas a persistencia dos eventos. Se eles são emitidos, ou não, está fora do escopo dssa implementação.
